### ISSUE TITLE
Message explaining model download

### ISSUE THREAD

**Issue by starchildluke** [jaketae/wordwise#12]
Firstly, I want to say how awesome this is and how I've been looking to solve the problem you had in your keyword extraction post that resulted in Wordwise (https://jaketae.github.io/study/keyword-extraction/)

Upon testing the example code, I noticed it immediately downloaded a couple of things which I assumed were language model files. However, I assumed that based on prior knowledge. I think a message or prompt would be beneficial to explain, since the user hasn't specified a particular model, they will be downloading a default one. I think will help anyone trying this out without similarly prior knowledge and I know Hugging Face does this with their transformers.

Thank you for your time and keep up the good work!

**Comment by jaketae** [comment]
Hi @starchildluke, thanks for opening this issue!

I definitely agree with you that a more informative message would be more user-friendly. This can probably be done by using the `logger`. I don't have the bandwidth to work on this right now at the moment, but I will try to work on it soon when I find time. If you would prefer, please feel free to open a PR to tackle this! Thanks again.

**Comment by starchildluke** [comment]
Hi @jaketae.

Thanks for your time. I fully appreciate the lack of bandwidth (I'm in a similar position myself) so no problem at all. Should I get the time or capacity, I might tackle this at some point but yeah, whenever you're up to it really.

**Comment by jaketae** [comment]
Hey @starchildluke, I'm closing this issue for now, but please feel free to ping me or open a new issue if you'd like to work on this. Thanks, and happy holidays!
