### ISSUE TITLE
Error: size of tensor a must match size of tensor b

### ISSUE THREAD

**Issue by smileservices** [jaketae/wordwise#13]
Getting the error `RuntimeError: The size of tensor a (5327) must match the size of tensor b (512) at non-singleton dimension 1` when running:

```python
from wordwise import Extractor

stripped_body = w3lib.html.remove_tags(text_with_html_tags).strip()
extractor = Extractor(spacy_model="en_core_web_trf")
keywords = extractor.generate(stripped_body, 6)
```

**Comment by jaketae** [comment]
Thank you for reporting this. Do you mind sharing your environment/packages via something like `pip list`?

**Comment by jaketae** [comment]
Hello @smileservices, I'm closing this for now, but please feel free to ping me here or open a new issue if this problem persists. Thanks!
